# Generated by Django 3.2.16 on 2022-11-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=300)),
                ('category_description', models.JSONField()),
                ('is_active', models.BooleanField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryStocksAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemsAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDelayAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestsAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=300)),
                ('item_branding_logo', models.CharField(max_length=200)),
                ('item_description', models.JSONField()),
                ('item_cost_price', models.IntegerField()),
                ('item_selling_price', models.IntegerField()),
                ('item_tax_slab', models.JSONField()),
                ('is_active', models.BooleanField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMS_Schema.category')),
            ],
        ),
    ]
